/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.platoon.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.platoon.ui.internal.PlatoonActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PlatoonExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PlatoonActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PlatoonActivator.getInstance().getInjector(PlatoonActivator.ORG_XTEXT_EXAMPLE_PLATOON_PLATOON);
	}
	
}
