/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.boundingbox.serializer;

import boundingbox.BoundingboxPackage;
import boundingbox.MoveDown;
import boundingbox.MoveLeft;
import boundingbox.MoveRight;
import boundingbox.MoveUp;
import boundingbox.World;
import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.boundingbox.services.BoundingBoxGrammarAccess;

@SuppressWarnings("all")
public class BoundingBoxSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private BoundingBoxGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == BoundingboxPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case BoundingboxPackage.MOVE_DOWN:
				sequence_MoveDown(context, (MoveDown) semanticObject); 
				return; 
			case BoundingboxPackage.MOVE_LEFT:
				sequence_MoveLeft(context, (MoveLeft) semanticObject); 
				return; 
			case BoundingboxPackage.MOVE_RIGHT:
				sequence_MoveRight(context, (MoveRight) semanticObject); 
				return; 
			case BoundingboxPackage.MOVE_UP:
				sequence_MoveUp(context, (MoveUp) semanticObject); 
				return; 
			case BoundingboxPackage.WORLD:
				sequence_World(context, (World) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Move returns MoveDown
	 *     MoveDown returns MoveDown
	 *
	 * Constraint:
	 *     distance=EInt
	 */
	protected void sequence_MoveDown(ISerializationContext context, MoveDown semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BoundingboxPackage.Literals.MOVE__DISTANCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BoundingboxPackage.Literals.MOVE__DISTANCE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMoveDownAccess().getDistanceEIntParserRuleCall_1_0(), semanticObject.getDistance());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Move returns MoveLeft
	 *     MoveLeft returns MoveLeft
	 *
	 * Constraint:
	 *     distance=EInt
	 */
	protected void sequence_MoveLeft(ISerializationContext context, MoveLeft semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BoundingboxPackage.Literals.MOVE__DISTANCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BoundingboxPackage.Literals.MOVE__DISTANCE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMoveLeftAccess().getDistanceEIntParserRuleCall_1_0(), semanticObject.getDistance());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Move returns MoveRight
	 *     MoveRight returns MoveRight
	 *
	 * Constraint:
	 *     distance=EInt
	 */
	protected void sequence_MoveRight(ISerializationContext context, MoveRight semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BoundingboxPackage.Literals.MOVE__DISTANCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BoundingboxPackage.Literals.MOVE__DISTANCE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMoveRightAccess().getDistanceEIntParserRuleCall_1_0(), semanticObject.getDistance());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Move returns MoveUp
	 *     MoveUp returns MoveUp
	 *
	 * Constraint:
	 *     distance=EInt
	 */
	protected void sequence_MoveUp(ISerializationContext context, MoveUp semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BoundingboxPackage.Literals.MOVE__DISTANCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BoundingboxPackage.Literals.MOVE__DISTANCE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMoveUpAccess().getDistanceEIntParserRuleCall_1_0(), semanticObject.getDistance());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     World returns World
	 *
	 * Constraint:
	 *     (moveCommands+=Move moveCommands+=Move*)?
	 */
	protected void sequence_World(ISerializationContext context, World semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
