/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.boundingbox.validation;

import org.xtext.example.boundingbox.validation.AbstractBoundingBoxValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BoundingBoxValidator extends AbstractBoundingBoxValidator {
}
