/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.boundingbox;

import org.xtext.example.boundingbox.BoundingBoxStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BoundingBoxStandaloneSetup extends BoundingBoxStandaloneSetupGenerated {
  public static void doSetup() {
    BoundingBoxStandaloneSetup _boundingBoxStandaloneSetup = new BoundingBoxStandaloneSetup();
    _boundingBoxStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
