/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.platoon.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PlatoonGrammarAccess extends AbstractGrammarElementFinder {
	
	public class RootElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.platoon.Platoon.Root");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPlatoonAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPlatoonPlatoonParserRuleCall_0_0 = (RuleCall)cPlatoonAssignment_0.eContents().get(0);
		private final Assignment cRouteAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRouteRouteParserRuleCall_1_0 = (RuleCall)cRouteAssignment_1.eContents().get(0);
		private final Assignment cConstraintsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cConstraintsConstraintsParserRuleCall_2_0 = (RuleCall)cConstraintsAssignment_2.eContents().get(0);
		
		//Root:
		//	platoon=Platoon
		//	route=Route
		//	constraints=Constraints;
		@Override public ParserRule getRule() { return rule; }
		
		//platoon=Platoon route=Route constraints=Constraints
		public Group getGroup() { return cGroup; }
		
		//platoon=Platoon
		public Assignment getPlatoonAssignment_0() { return cPlatoonAssignment_0; }
		
		//Platoon
		public RuleCall getPlatoonPlatoonParserRuleCall_0_0() { return cPlatoonPlatoonParserRuleCall_0_0; }
		
		//route=Route
		public Assignment getRouteAssignment_1() { return cRouteAssignment_1; }
		
		//Route
		public RuleCall getRouteRouteParserRuleCall_1_0() { return cRouteRouteParserRuleCall_1_0; }
		
		//constraints=Constraints
		public Assignment getConstraintsAssignment_2() { return cConstraintsAssignment_2; }
		
		//Constraints
		public RuleCall getConstraintsConstraintsParserRuleCall_2_0() { return cConstraintsConstraintsParserRuleCall_2_0; }
	}
	public class RouteCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.platoon.Platoon.routeCommand");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cForwardParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTurnLeftParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTurnRightParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//routeCommand:
		//	Forward | TurnLeft | TurnRight;
		@Override public ParserRule getRule() { return rule; }
		
		//Forward | TurnLeft | TurnRight
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Forward
		public RuleCall getForwardParserRuleCall_0() { return cForwardParserRuleCall_0; }
		
		//TurnLeft
		public RuleCall getTurnLeftParserRuleCall_1() { return cTurnLeftParserRuleCall_1; }
		
		//TurnRight
		public RuleCall getTurnRightParserRuleCall_2() { return cTurnRightParserRuleCall_2; }
	}
	public class VehicleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.platoon.Platoon.Vehicle");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFollowingVehicleParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLeaderVehicleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Vehicle:
		//	FollowingVehicle | LeaderVehicle;
		@Override public ParserRule getRule() { return rule; }
		
		//FollowingVehicle | LeaderVehicle
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FollowingVehicle
		public RuleCall getFollowingVehicleParserRuleCall_0() { return cFollowingVehicleParserRuleCall_0; }
		
		//LeaderVehicle
		public RuleCall getLeaderVehicleParserRuleCall_1() { return cLeaderVehicleParserRuleCall_1; }
	}
	public class PlatoonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.platoon.Platoon.Platoon");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlatoonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLeaderVehicleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLeaderVehicleLeaderVehicleParserRuleCall_1_0 = (RuleCall)cLeaderVehicleAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cFollowingVehicleAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cFollowingVehicleFollowingVehicleParserRuleCall_2_0_0 = (RuleCall)cFollowingVehicleAssignment_2_0.eContents().get(0);
		private final Assignment cFollowingVehicleAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cFollowingVehicleFollowingVehicleParserRuleCall_2_1_0 = (RuleCall)cFollowingVehicleAssignment_2_1.eContents().get(0);
		
		//Platoon:
		//	'platoon:'
		//	leaderVehicle=LeaderVehicle (followingVehicle+=FollowingVehicle followingVehicle+=FollowingVehicle*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'platoon:' leaderVehicle=LeaderVehicle (followingVehicle+=FollowingVehicle followingVehicle+=FollowingVehicle*)?
		public Group getGroup() { return cGroup; }
		
		//'platoon:'
		public Keyword getPlatoonKeyword_0() { return cPlatoonKeyword_0; }
		
		//leaderVehicle=LeaderVehicle
		public Assignment getLeaderVehicleAssignment_1() { return cLeaderVehicleAssignment_1; }
		
		//LeaderVehicle
		public RuleCall getLeaderVehicleLeaderVehicleParserRuleCall_1_0() { return cLeaderVehicleLeaderVehicleParserRuleCall_1_0; }
		
		//(followingVehicle+=FollowingVehicle followingVehicle+=FollowingVehicle*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//followingVehicle+=FollowingVehicle
		public Assignment getFollowingVehicleAssignment_2_0() { return cFollowingVehicleAssignment_2_0; }
		
		//FollowingVehicle
		public RuleCall getFollowingVehicleFollowingVehicleParserRuleCall_2_0_0() { return cFollowingVehicleFollowingVehicleParserRuleCall_2_0_0; }
		
		//followingVehicle+=FollowingVehicle*
		public Assignment getFollowingVehicleAssignment_2_1() { return cFollowingVehicleAssignment_2_1; }
		
		//FollowingVehicle
		public RuleCall getFollowingVehicleFollowingVehicleParserRuleCall_2_1_0() { return cFollowingVehicleFollowingVehicleParserRuleCall_2_1_0; }
	}
	public class RouteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.platoon.Platoon.Route");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRouteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRouteCommandsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRouteCommandsRouteCommandParserRuleCall_3_0 = (RuleCall)cRouteCommandsAssignment_3.eContents().get(0);
		private final Assignment cRouteCommandsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRouteCommandsRouteCommandParserRuleCall_4_0 = (RuleCall)cRouteCommandsAssignment_4.eContents().get(0);
		
		//Route:
		//	'route'
		//	name=EString
		//	':'
		//	routeCommands+=routeCommand routeCommands+=routeCommand*;
		@Override public ParserRule getRule() { return rule; }
		
		//'route' name=EString ':' routeCommands+=routeCommand routeCommands+=routeCommand*
		public Group getGroup() { return cGroup; }
		
		//'route'
		public Keyword getRouteKeyword_0() { return cRouteKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//routeCommands+=routeCommand
		public Assignment getRouteCommandsAssignment_3() { return cRouteCommandsAssignment_3; }
		
		//routeCommand
		public RuleCall getRouteCommandsRouteCommandParserRuleCall_3_0() { return cRouteCommandsRouteCommandParserRuleCall_3_0; }
		
		//routeCommands+=routeCommand*
		public Assignment getRouteCommandsAssignment_4() { return cRouteCommandsAssignment_4; }
		
		//routeCommand
		public RuleCall getRouteCommandsRouteCommandParserRuleCall_4_0() { return cRouteCommandsRouteCommandParserRuleCall_4_0; }
	}
	public class ConstraintsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.platoon.Platoon.Constraints");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConstraintsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLboundAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLboundEIntParserRuleCall_1_0 = (RuleCall)cLboundAssignment_1.eContents().get(0);
		private final Keyword cLessThanSignEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cHeadwayKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLessThanSignEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cUboundAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cUboundEIntParserRuleCall_5_0 = (RuleCall)cUboundAssignment_5.eContents().get(0);
		
		//Constraints:
		//	'constraints:'
		//	lbound=EInt '<=' 'headway' '<=' ubound=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//'constraints:' lbound=EInt '<=' 'headway' '<=' ubound=EInt
		public Group getGroup() { return cGroup; }
		
		//'constraints:'
		public Keyword getConstraintsKeyword_0() { return cConstraintsKeyword_0; }
		
		//lbound=EInt
		public Assignment getLboundAssignment_1() { return cLboundAssignment_1; }
		
		//EInt
		public RuleCall getLboundEIntParserRuleCall_1_0() { return cLboundEIntParserRuleCall_1_0; }
		
		//'<='
		public Keyword getLessThanSignEqualsSignKeyword_2() { return cLessThanSignEqualsSignKeyword_2; }
		
		//'headway'
		public Keyword getHeadwayKeyword_3() { return cHeadwayKeyword_3; }
		
		//'<='
		public Keyword getLessThanSignEqualsSignKeyword_4() { return cLessThanSignEqualsSignKeyword_4; }
		
		//ubound=EInt
		public Assignment getUboundAssignment_5() { return cUboundAssignment_5; }
		
		//EInt
		public RuleCall getUboundEIntParserRuleCall_5_0() { return cUboundEIntParserRuleCall_5_0; }
	}
	public class LeaderVehicleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.platoon.Platoon.LeaderVehicle");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLVKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cRouteKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRouteAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cRouteRouteCrossReference_3_0 = (CrossReference)cRouteAssignment_3.eContents().get(0);
		private final RuleCall cRouteRouteEStringParserRuleCall_3_0_1 = (RuleCall)cRouteRouteCrossReference_3_0.eContents().get(1);
		
		//LeaderVehicle:
		//	'LV'
		//	name=EString
		//	'route' route=[Route|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//'LV' name=EString 'route' route=[Route|EString]
		public Group getGroup() { return cGroup; }
		
		//'LV'
		public Keyword getLVKeyword_0() { return cLVKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'route'
		public Keyword getRouteKeyword_2() { return cRouteKeyword_2; }
		
		//route=[Route|EString]
		public Assignment getRouteAssignment_3() { return cRouteAssignment_3; }
		
		//[Route|EString]
		public CrossReference getRouteRouteCrossReference_3_0() { return cRouteRouteCrossReference_3_0; }
		
		//EString
		public RuleCall getRouteRouteEStringParserRuleCall_3_0_1() { return cRouteRouteEStringParserRuleCall_3_0_1; }
	}
	public class FollowingVehicleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.platoon.Platoon.FollowingVehicle");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFVKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cFrontKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cRunnerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFollowingAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cFollowingVehicleCrossReference_4_0 = (CrossReference)cFollowingAssignment_4.eContents().get(0);
		private final RuleCall cFollowingVehicleEStringParserRuleCall_4_0_1 = (RuleCall)cFollowingVehicleCrossReference_4_0.eContents().get(1);
		
		//FollowingVehicle:
		//	'FV'
		//	name=EString
		//	'front' 'runner' following=[Vehicle|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//'FV' name=EString 'front' 'runner' following=[Vehicle|EString]
		public Group getGroup() { return cGroup; }
		
		//'FV'
		public Keyword getFVKeyword_0() { return cFVKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'front'
		public Keyword getFrontKeyword_2() { return cFrontKeyword_2; }
		
		//'runner'
		public Keyword getRunnerKeyword_3() { return cRunnerKeyword_3; }
		
		//following=[Vehicle|EString]
		public Assignment getFollowingAssignment_4() { return cFollowingAssignment_4; }
		
		//[Vehicle|EString]
		public CrossReference getFollowingVehicleCrossReference_4_0() { return cFollowingVehicleCrossReference_4_0; }
		
		//EString
		public RuleCall getFollowingVehicleEStringParserRuleCall_4_0_1() { return cFollowingVehicleEStringParserRuleCall_4_0_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.platoon.Platoon.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ForwardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.platoon.Platoon.Forward");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cForwardKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDistanceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDistanceEIntParserRuleCall_2_0 = (RuleCall)cDistanceAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Forward:
		//	'forward'
		//	'('
		//	distance=EInt
		//	')';
		@Override public ParserRule getRule() { return rule; }
		
		//'forward' '(' distance=EInt ')'
		public Group getGroup() { return cGroup; }
		
		//'forward'
		public Keyword getForwardKeyword_0() { return cForwardKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//distance=EInt
		public Assignment getDistanceAssignment_2() { return cDistanceAssignment_2; }
		
		//EInt
		public RuleCall getDistanceEIntParserRuleCall_2_0() { return cDistanceEIntParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class TurnLeftElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.platoon.Platoon.TurnLeft");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTurnLeftAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTurnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//TurnLeft:
		//	{TurnLeft}
		//	'turn' 'Left';
		@Override public ParserRule getRule() { return rule; }
		
		//{TurnLeft} 'turn' 'Left'
		public Group getGroup() { return cGroup; }
		
		//{TurnLeft}
		public Action getTurnLeftAction_0() { return cTurnLeftAction_0; }
		
		//'turn'
		public Keyword getTurnKeyword_1() { return cTurnKeyword_1; }
		
		//'Left'
		public Keyword getLeftKeyword_2() { return cLeftKeyword_2; }
	}
	public class TurnRightElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.platoon.Platoon.TurnRight");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTurnRightAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTurnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRightKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//TurnRight:
		//	{TurnRight}
		//	'turn' 'Right';
		@Override public ParserRule getRule() { return rule; }
		
		//{TurnRight} 'turn' 'Right'
		public Group getGroup() { return cGroup; }
		
		//{TurnRight}
		public Action getTurnRightAction_0() { return cTurnRightAction_0; }
		
		//'turn'
		public Keyword getTurnKeyword_1() { return cTurnKeyword_1; }
		
		//'Right'
		public Keyword getRightKeyword_2() { return cRightKeyword_2; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.platoon.Platoon.EInt");
		private final RuleCall cINTTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//EInt ecore::EInt:
		//	INT
		@Override public ParserRule getRule() { return rule; }
		
		//INT
		public RuleCall getINTTerminalRuleCall() { return cINTTerminalRuleCall; }
	}
	
	
	private final RootElements pRoot;
	private final RouteCommandElements pRouteCommand;
	private final VehicleElements pVehicle;
	private final PlatoonElements pPlatoon;
	private final RouteElements pRoute;
	private final ConstraintsElements pConstraints;
	private final LeaderVehicleElements pLeaderVehicle;
	private final FollowingVehicleElements pFollowingVehicle;
	private final EStringElements pEString;
	private final ForwardElements pForward;
	private final TurnLeftElements pTurnLeft;
	private final TurnRightElements pTurnRight;
	private final EIntElements pEInt;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PlatoonGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRoot = new RootElements();
		this.pRouteCommand = new RouteCommandElements();
		this.pVehicle = new VehicleElements();
		this.pPlatoon = new PlatoonElements();
		this.pRoute = new RouteElements();
		this.pConstraints = new ConstraintsElements();
		this.pLeaderVehicle = new LeaderVehicleElements();
		this.pFollowingVehicle = new FollowingVehicleElements();
		this.pEString = new EStringElements();
		this.pForward = new ForwardElements();
		this.pTurnLeft = new TurnLeftElements();
		this.pTurnRight = new TurnRightElements();
		this.pEInt = new EIntElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.platoon.Platoon".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Root:
	//	platoon=Platoon
	//	route=Route
	//	constraints=Constraints;
	public RootElements getRootAccess() {
		return pRoot;
	}
	
	public ParserRule getRootRule() {
		return getRootAccess().getRule();
	}
	
	//routeCommand:
	//	Forward | TurnLeft | TurnRight;
	public RouteCommandElements getRouteCommandAccess() {
		return pRouteCommand;
	}
	
	public ParserRule getRouteCommandRule() {
		return getRouteCommandAccess().getRule();
	}
	
	//Vehicle:
	//	FollowingVehicle | LeaderVehicle;
	public VehicleElements getVehicleAccess() {
		return pVehicle;
	}
	
	public ParserRule getVehicleRule() {
		return getVehicleAccess().getRule();
	}
	
	//Platoon:
	//	'platoon:'
	//	leaderVehicle=LeaderVehicle (followingVehicle+=FollowingVehicle followingVehicle+=FollowingVehicle*)?;
	public PlatoonElements getPlatoonAccess() {
		return pPlatoon;
	}
	
	public ParserRule getPlatoonRule() {
		return getPlatoonAccess().getRule();
	}
	
	//Route:
	//	'route'
	//	name=EString
	//	':'
	//	routeCommands+=routeCommand routeCommands+=routeCommand*;
	public RouteElements getRouteAccess() {
		return pRoute;
	}
	
	public ParserRule getRouteRule() {
		return getRouteAccess().getRule();
	}
	
	//Constraints:
	//	'constraints:'
	//	lbound=EInt '<=' 'headway' '<=' ubound=EInt;
	public ConstraintsElements getConstraintsAccess() {
		return pConstraints;
	}
	
	public ParserRule getConstraintsRule() {
		return getConstraintsAccess().getRule();
	}
	
	//LeaderVehicle:
	//	'LV'
	//	name=EString
	//	'route' route=[Route|EString];
	public LeaderVehicleElements getLeaderVehicleAccess() {
		return pLeaderVehicle;
	}
	
	public ParserRule getLeaderVehicleRule() {
		return getLeaderVehicleAccess().getRule();
	}
	
	//FollowingVehicle:
	//	'FV'
	//	name=EString
	//	'front' 'runner' following=[Vehicle|EString];
	public FollowingVehicleElements getFollowingVehicleAccess() {
		return pFollowingVehicle;
	}
	
	public ParserRule getFollowingVehicleRule() {
		return getFollowingVehicleAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Forward:
	//	'forward'
	//	'('
	//	distance=EInt
	//	')';
	public ForwardElements getForwardAccess() {
		return pForward;
	}
	
	public ParserRule getForwardRule() {
		return getForwardAccess().getRule();
	}
	
	//TurnLeft:
	//	{TurnLeft}
	//	'turn' 'Left';
	public TurnLeftElements getTurnLeftAccess() {
		return pTurnLeft;
	}
	
	public ParserRule getTurnLeftRule() {
		return getTurnLeftAccess().getRule();
	}
	
	//TurnRight:
	//	{TurnRight}
	//	'turn' 'Right';
	public TurnRightElements getTurnRightAccess() {
		return pTurnRight;
	}
	
	public ParserRule getTurnRightRule() {
		return getTurnRightAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	INT
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
