/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.platoon.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PlatoonAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/platoon/parser/antlr/internal/InternalPlatoon.tokens");
	}
}
