/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.boundingbox.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.boundingbox.ui.AbstractBoundingBoxUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BoundingBoxUiModule extends AbstractBoundingBoxUiModule {
  public BoundingBoxUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
