/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.boundingbox.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.boundingbox.ui.internal.BoundingboxActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BoundingBoxExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BoundingboxActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BoundingboxActivator.getInstance().getInjector(BoundingboxActivator.ORG_XTEXT_EXAMPLE_BOUNDINGBOX_BOUNDINGBOX);
	}
	
}
