/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.platoon.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import platoon.Root

@RunWith(XtextRunner)
@InjectWith(PlatoonInjectorProvider)
class PlatoonParsingTest{

	@Inject
	ParseHelper<Root> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
