/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.boundingbox


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BoundingBoxStandaloneSetup extends BoundingBoxStandaloneSetupGenerated {

	def static void doSetup() {
		new BoundingBoxStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
