/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.platoon.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.platoon.ui.AbstractPlatoonUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PlatoonUiModule extends AbstractPlatoonUiModule {
  public PlatoonUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
