/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.platoon;

import org.xtext.example.platoon.PlatoonStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PlatoonStandaloneSetup extends PlatoonStandaloneSetupGenerated {
  public static void doSetup() {
    PlatoonStandaloneSetup _platoonStandaloneSetup = new PlatoonStandaloneSetup();
    _platoonStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
