/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.platoon;

import org.xtext.example.platoon.AbstractPlatoonRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PlatoonRuntimeModule extends AbstractPlatoonRuntimeModule {
}
