/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.boundingbox.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.example.boundingbox.ide.contentassist.antlr.internal.InternalBoundingBoxParser;
import org.xtext.example.boundingbox.services.BoundingBoxGrammarAccess;

public class BoundingBoxParser extends AbstractContentAssistParser {

	@Inject
	private BoundingBoxGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalBoundingBoxParser createParser() {
		InternalBoundingBoxParser result = new InternalBoundingBoxParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getMoveAccess().getAlternatives(), "rule__Move__Alternatives");
					put(grammarAccess.getWorldAccess().getGroup(), "rule__World__Group__0");
					put(grammarAccess.getWorldAccess().getGroup_3(), "rule__World__Group_3__0");
					put(grammarAccess.getMoveLeftAccess().getGroup(), "rule__MoveLeft__Group__0");
					put(grammarAccess.getMoveRightAccess().getGroup(), "rule__MoveRight__Group__0");
					put(grammarAccess.getMoveUpAccess().getGroup(), "rule__MoveUp__Group__0");
					put(grammarAccess.getMoveDownAccess().getGroup(), "rule__MoveDown__Group__0");
					put(grammarAccess.getWorldAccess().getMoveCommandsAssignment_3_0(), "rule__World__MoveCommandsAssignment_3_0");
					put(grammarAccess.getWorldAccess().getMoveCommandsAssignment_3_1(), "rule__World__MoveCommandsAssignment_3_1");
					put(grammarAccess.getMoveLeftAccess().getDistanceAssignment_1(), "rule__MoveLeft__DistanceAssignment_1");
					put(grammarAccess.getMoveRightAccess().getDistanceAssignment_1(), "rule__MoveRight__DistanceAssignment_1");
					put(grammarAccess.getMoveUpAccess().getDistanceAssignment_1(), "rule__MoveUp__DistanceAssignment_1");
					put(grammarAccess.getMoveDownAccess().getDistanceAssignment_1(), "rule__MoveDown__DistanceAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalBoundingBoxParser typedParser = (InternalBoundingBoxParser) parser;
			typedParser.entryRuleWorld();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public BoundingBoxGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BoundingBoxGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
