/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.boundingbox.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.boundingbox.ui.internal.BoundingboxActivator;

public class BoundingBoxUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BoundingboxActivator.getInstance().getInjector("org.xtext.example.boundingbox.BoundingBox");
	}

}
