/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.boundingbox.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.boundingbox.parser.antlr.internal.InternalBoundingBoxParser;
import org.xtext.example.boundingbox.services.BoundingBoxGrammarAccess;

public class BoundingBoxParser extends AbstractAntlrParser {

	@Inject
	private BoundingBoxGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBoundingBoxParser createParser(XtextTokenStream stream) {
		return new InternalBoundingBoxParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "World";
	}

	public BoundingBoxGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BoundingBoxGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
