/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.platoon.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPlatoonScopeProvider extends DelegatingScopeProvider {
}
